using UnityEditor;
using UnityEngine;
using System.Text;
using System.IO;
using System.Linq;
using System.Collections.Generic;
namespace Koto.UIAutoBind
{
    public static class UIBindGenerator
    {
        public static void Generate(UIBindBehaviour ui)
        {
            if (ui == null) return;

            var binds = UIBindResolver.GetBinds(ui);

            for (int i = 0; i < binds.Length; i++)
            {
                Undo.RecordObject(binds[i], "Assign UIBind Index");
                binds[i].Editor_SetIndex(i);
                EditorUtility.SetDirty(binds[i]);
            }

            GeneratePartial(ui, binds);
        }

        static void GeneratePartial(UIBindBehaviour ui, UIBindMarker[] binds)
        {
            var type = ui.GetType();
            var ns = type.Namespace;
            var className = type.Name;

            var namespaces = new HashSet<string>
        {
            "UnityEngine"
        };

            // 收集命名空间
            foreach (var bind in binds)
            {
                var c = UIBindResolver.Resolve(bind);
                if (c != null && !string.IsNullOrEmpty(c.GetType().Namespace))
                    namespaces.Add(c.GetType().Namespace);
            }

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb, ui);
            // using
            foreach (var use in namespaces)
                sb.AppendLine($"using {use};");

            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");

            // =====================
            // 字段声明
            // =====================

            var usedNames = new HashSet<string>();
            for (int i = 0; i < binds.Length; i++)
            {
                var bind = binds[i];
                var comp = UIBindResolver.Resolve(bind);
                if (comp == null) continue;

                var fieldName = MakeFieldName(comp, bind, usedNames);
                var typeName = comp.GetType().Name;
                sb.AppendLine("        [UIAutoBind]");
                sb.AppendLine(
                    $"        private {typeName} {fieldName};"
                );
            }

            sb.AppendLine();
            sb.AppendLine("        protected override void GetUI()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.GetUI();");

            // =====================
            // 赋值
            // =====================
            usedNames.Clear();
            for (int i = 0; i < binds.Length; i++)
            {
                var bind = binds[i];
                var comp = UIBindResolver.Resolve(bind);
                if (comp == null) continue;

                var fieldName = MakeFieldName(comp, bind, usedNames);
                var typeName = comp.GetType().Name;

                sb.AppendLine(
                    $"            {fieldName} = GetBind<{typeName}>({i});"
                );
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine("}");

            var dir = ui.GeneratedScriptPath;
            if (!IsValidGeneratePath(dir, out var error))
            {
                EditorUtility.DisplayDialog(
                    "UI AutoBind 生成失败",
                    error,
                    "OK"
                );
                return;
            }
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            var path = Path.Combine(dir, $"{className}.Bind.g.cs");
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            AssetDatabase.Refresh();
        }

        // =====================
        // 命名工具
        // =====================
        public static string MakeFieldName(
            Component comp,
            UIBindMarker bind,
            HashSet<string> existedNames
        )
        {
            // 1️⃣ 最短优先：只用节点名
            string baseName = MakeFieldBaseName(bind);

            if (existedNames.Add(baseName))
                return baseName;

            // 2️⃣ 冲突：加类型
            string typeAbbrev = GetTypeAbbrev(comp);
            string withType = $"{baseName}_{typeAbbrev}";

            if (existedNames.Add(withType))
                return withType;

            // 3️⃣ 仍冲突：加索引
            int index = 1;
            while (true)
            {
                string indexed = $"{withType}{index}";
                if (existedNames.Add(indexed))
                    return indexed;
                index++;
            }
        }

        /// <summary>
        /// 生成基础字段名（不含类型）
        /// </summary>
        private static string MakeFieldBaseName(UIBindMarker bind)
        {
            var nodeName = MakeSafeFieldName(bind.name);
            return $"_{nodeName}";
        }

        /// <summary>
        /// 类型缩写（仅在冲突时使用）
        /// </summary>
        private static string GetTypeAbbrev(Component comp)
        {
            return comp.GetType().Name switch
            {
                "TextMeshProUGUI" => "TMPText",
                "TMP_InputField" => "TMPInput",
                "TMP_Dropdown" => "TMPDrop",
                "ContentSizeFitter" => "CSF",
                "AspectRatioFitter" => "ARF",
                "LayoutElement" => "LElm",
                "VerticalLayoutGroup" => "VLG",
                "HorizontalLayoutGroup" => "HLG",
                "GridLayoutGroup" => "GLG",

                _ => comp.GetType().Name
            };
        }

        static string MakeSafeFieldName(string name)
        {
            var sb = new StringBuilder(name.Length + 2);

            if (!char.IsLetter(name[0]) && name[0] != '_')
                sb.Append('_');

            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            return sb.ToString();
        }

        static bool IsValidGeneratePath(string path, out string error)
        {
            error = null;

            if (string.IsNullOrEmpty(path))
            {
                error = "生成路径为空";
                return false;
            }

            path = path.Replace("\\", "/");

            if (path.StartsWith("Assets/Packages") ||
                path.StartsWith("Assets/Library"))
            {
                error = "禁止生成到 Packages / Library 目录";
                return false;
            }

            return true;
        }
        static void AppendAutoGeneratedHeader(StringBuilder sb, UIBindBehaviour ui)
        {
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <自动生成>");
            sb.AppendLine("//     本文件由 UIAutoBindGenerator 自动生成");
            sb.AppendLine("//     请勿手动修改此文件，重新生成将覆盖所有改动");
            sb.AppendLine("//");
            sb.AppendLine($"//     来源 UI : {ui.GetType().FullName}");
            sb.AppendLine($"//     生成时间 : {System.DateTime.Now:yyyy-MM-dd}");
            sb.AppendLine("// </自动生成>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
        }

    }
}